-- MySQL Script generated by MySQL Workbench
-- Sun Jan 19 03:32:50 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_ragemp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_ragemp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_ragemp` DEFAULT CHARACTER SET utf8 ;
USE `db_ragemp` ;

-- -----------------------------------------------------
-- Table `db_ragemp`.`gangs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ragemp`.`gangs` (
  `gangId` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(50) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `tag` VARCHAR(5) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  `money` FLOAT NOT NULL,
  `color` VARCHAR(10) NOT NULL,
  `levelVipGang` INT NOT NULL DEFAULT 0,
  `levelPlayer` INT NOT NULL DEFAULT 1,
  `expPlayer` INT NOT NULL DEFAULT 0,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`gangId`),
  UNIQUE INDEX `id_UNIQUE` (`gangId` ASC),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC));


-- -----------------------------------------------------
-- Table `db_ragemp`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ragemp`.`users` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(50) NOT NULL,
  `username` VARCHAR(50) NOT NULL,
  `email` VARCHAR(254) NOT NULL,
  `password` VARCHAR(72) NOT NULL,
  `socialClub` VARCHAR(20) NOT NULL,
  `socialClubId` INT NOT NULL,
  `money` FLOAT NOT NULL DEFAULT 0.0,
  `cash` INT NOT NULL DEFAULT 0,
  `kills` INT NOT NULL DEFAULT 0,
  `deaths` INT NOT NULL DEFAULT 0,
  `levelAdmin` INT NOT NULL DEFAULT 0,
  `levelGang` INT NOT NULL DEFAULT 0,
  `levelVip` INT NOT NULL DEFAULT 0,
  `levelGang` INT NOT NULL DEFAULT 1,
  `expGang` INT NOT NULL DEFAULT 0,
  `position` VARCHAR(100) NULL,
  `onlineTime` INT NOT NULL DEFAULT 0,
  `lastActive` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `gangId` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`userId`, `gangId`),
  UNIQUE INDEX `id_UNIQUE` (`userId` ASC),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC),
  INDEX `fk_user_gang1_idx` (`gangId` ASC),
  CONSTRAINT `fk_user_gang1`
    FOREIGN KEY (`gangId`)
    REFERENCES `db_ragemp`.`gangs` (`gangId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `db_ragemp`.`vehicles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ragemp`.`vehicles` (
  `vehicleId` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(50) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `price` FLOAT NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`vehicleId`),
  UNIQUE INDEX `id_UNIQUE` (`vehicleId` ASC),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC));


-- -----------------------------------------------------
-- Table `db_ragemp`.`bans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ragemp`.`bans` (
  `banId` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(50) NOT NULL,
  `reason` VARCHAR(100) NOT NULL,
  `startDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `endDate` TIMESTAMP NULL,
  `userId` INT NOT NULL,
  PRIMARY KEY (`banId`, `userId`),
  UNIQUE INDEX `id_UNIQUE` (`banId` ASC),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC),
  INDEX `fk_bans_user1_idx` (`userId` ASC),
  CONSTRAINT `fk_bans_user1`
    FOREIGN KEY (`userId`)
    REFERENCES `db_ragemp`.`users` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `db_ragemp`.`logs_chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ragemp`.`logs_chat` (
  `logChatId` INT NOT NULL AUTO_INCREMENT,
  `message` VARCHAR(255) NOT NULL,
  `type` INT NOT NULL DEFAULT 0,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `userId` INT NOT NULL,
  PRIMARY KEY (`logChatId`, `userId`),
  UNIQUE INDEX `id_UNIQUE` (`logChatId` ASC),
  INDEX `fk_logChat_user1_idx` (`userId` ASC),
  CONSTRAINT `fk_logChat_user1`
    FOREIGN KEY (`userId`)
    REFERENCES `db_ragemp`.`users` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `db_ragemp`.`logs_admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ragemp`.`logs_admin` (
  `logChatId` INT NOT NULL AUTO_INCREMENT,
  `action` VARCHAR(45) NOT NULL,
  `details` VARCHAR(255) NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `adminId` INT NOT NULL,
  `targetId` INT NOT NULL,
  PRIMARY KEY (`logChatId`, `adminId`, `targetId`),
  UNIQUE INDEX `id_UNIQUE` (`logChatId` ASC),
  INDEX `fk_logAdmin_user1_idx` (`adminId` ASC),
  INDEX `fk_logAdmin_user2_idx` (`targetId` ASC),
  CONSTRAINT `fk_logAdmin_user1`
    FOREIGN KEY (`adminId`)
    REFERENCES `db_ragemp`.`users` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_logAdmin_user2`
    FOREIGN KEY (`targetId`)
    REFERENCES `db_ragemp`.`users` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `db_ragemp`.`users_vehicles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ragemp`.`users_vehicles` (
  `userId` INT NOT NULL,
  `vehicleId` INT NOT NULL,
  PRIMARY KEY (`userId`, `vehicleId`),
  INDEX `fk_vehicle_has_user_user1_idx` (`userId` ASC),
  INDEX `fk_vehicle_has_user_vehicle1_idx` (`vehicleId` ASC),
  CONSTRAINT `fk_vehicle_has_user_vehicle1`
    FOREIGN KEY (`vehicleId`)
    REFERENCES `db_ragemp`.`vehicles` (`vehicleId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vehicle_has_user_user1`
    FOREIGN KEY (`userId`)
    REFERENCES `db_ragemp`.`users` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `db_ragemp`.`logs_death`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ragemp`.`logs_death` (
  `logDeathId` INT NOT NULL AUTO_INCREMENT,
  `event` INT NOT NULL DEFAULT 0,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `killerId` INT NOT NULL,
  `deadId` INT NOT NULL,
  `killerGangId` INT NOT NULL,
  `deadGangId` INT NOT NULL,
  PRIMARY KEY (`logDeathId`, `killerId`, `deadId`, `killerGangId`, `deadGangId`),
  UNIQUE INDEX `id_UNIQUE` (`logDeathId` ASC),
  INDEX `fk_logDeaths_user1_idx` (`killerId` ASC, `killerGangId` ASC),
  INDEX `fk_logDeaths_user2_idx` (`deadId` ASC, `deadGangId` ASC),
  CONSTRAINT `fk_logDeaths_user1`
    FOREIGN KEY (`killerId` , `killerGangId`)
    REFERENCES `db_ragemp`.`users` (`userId` , `gangId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_logDeaths_user2`
    FOREIGN KEY (`deadId` , `deadGangId`)
    REFERENCES `db_ragemp`.`users` (`userId` , `gangId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `db_ragemp`.`logs_login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ragemp`.`logs_login` (
  `logLoginId` INT NOT NULL AUTO_INCREMENT,
  `ip` VARCHAR(16) NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `userId` INT NOT NULL,
  PRIMARY KEY (`logLoginId`, `userId`),
  INDEX `fk_logLogin_user1_idx` (`userId` ASC),
  CONSTRAINT `fk_logLogin_user1`
    FOREIGN KEY (`userId`)
    REFERENCES `db_ragemp`.`users` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_ragemp`.`logs_join`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ragemp`.`logs_join` (
  `logLoginId` INT NOT NULL AUTO_INCREMENT,
  `ip` VARCHAR(16) NOT NULL,
  `socialClub` VARCHAR(16) NULL,
  `serial` VARCHAR(128) NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`logLoginId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_ragemp`.`logs_transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ragemp`.`logs_transaction` (
  `logTransactionId` INT NOT NULL AUTO_INCREMENT,
  `amount` FLOAT NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `senderId` INT NOT NULL,
  `receiverId` INT NOT NULL,
  PRIMARY KEY (`logTransactionId`, `senderId`, `receiverId`),
  INDEX `fk_logBank_user1_idx` (`senderId` ASC),
  INDEX `fk_logBank_user2_idx` (`receiverId` ASC),
  CONSTRAINT `fk_logBank_user1`
    FOREIGN KEY (`senderId`)
    REFERENCES `db_ragemp`.`users` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_logBank_user2`
    FOREIGN KEY (`receiverId`)
    REFERENCES `db_ragemp`.`users` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Insert Gang 
-- -----------------------------------------------------

INSERT INTO `db_ragemp`.`gangs` 
  SET `uuid` = '09c88890-7736-4857-b42a-5b9741f65df8', `name` = 'Player', `tag` = 'Play', `description` = 'Player', `money` = 0, `color` = '3d3d3d';

ALTER TABLE `db_ragemp`.`users` 
ADD COLUMN `levelVip` INT NOT NULL DEFAULT 0;